name: Long Runtime Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show start time
        run: date

      - name: Wait 6 hours
        run: sleep 21600

      - name: Show end time
        run: date
